---
- hosts: all
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
    - arcanist
    - fonts
    - vim
    - xcode
    - dock

  tasks:
    - include: tasks/preferences.yml

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    - name: Run .osx dotfiles.
      shell: ~/.osx.sh --no-restart
      changed_when: false


